---
# vars file for roles/db-tier
db-pkg:
  - mariadb
  - mariadb-server
  - mysql-python
  - firewalld
db_srv: mariadb
db:
  user: root
  database: userdb
  password: redhat
  backupfile: userdb.backup
  