---
# tasks file for roles/db-tier
- name: Install mysql
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - "{{ db_pkg }}"

- name: Start mysql
  service:
    name: "{{ db_srv }}"
    enabled: true
    state: started
    